// src/components/Navbar.vue
<template>
  <nav
    class="fixed top-0 left-0 right-0 z-50 h-16 flex items-center justify-between px-8 transition-all duration-300"
    :class="scrolled ? 'bg-trae-bg/85 backdrop-blur-xl border-b border-white/5' : 'bg-trae-bg/55 backdrop-blur-md'"
  >
    <router-link to="/" class="flex items-center gap-2.5 no-underline">
      <div class="w-7 h-7 rounded-lg bg-gradient-to-br from-trae-accent to-trae-accent-deep grid place-items-center text-black font-extrabold text-sm shadow-[0_0_16px_rgba(34,197,94,0.35)]">
        T
      </div>
      <span class="text-trae-text font-bold text-base tracking-wide">TRAE Demo Wall</span>
    </router-link>

    <div class="flex items-center gap-4">
      <router-link
        to="/"
        class="px-4 py-2 rounded-trae-pill text-sm font-medium text-trae-text-secondary hover:text-trae-text transition-colors no-underline"
        active-class="!text-trae-text bg-trae-accent/10"
      >
        首页
      </router-link>
      <a
        href="https://forum.trae.cn/c/38-category/40-category/40"
        target="_blank"
        rel="noopener"
        class="px-4 py-2 rounded-trae-pill text-sm font-medium text-trae-text-secondary hover:text-trae-text transition-colors no-underline"
      >
        大赛论坛
      </a>
      <a
        href="https://github.com/luoqianshi/trae-demo-wall"
        target="_blank"
        rel="noopener"
        class="px-4 py-2 rounded-trae-pill text-sm font-medium text-trae-text-secondary hover:text-trae-text transition-colors no-underline"
      >
        GitHub
      </a>
    </div>
  </nav>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const scrolled = ref(false)

function onScroll() {
  scrolled.value = window.scrollY > 50
}

onMounted(() => window.addEventListener('scroll', onScroll))
onUnmounted(() => window.removeEventListener('scroll', onScroll))
</script>

// public/demos/topic_66911/src/components/Navbar.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { BookOpen, LayoutDashboard, PlusCircle, BarChart3, Menu, X } from 'lucide-react'

const navItems = [
  { href: '/', label: '首页', icon: BookOpen },
  { href: '/dashboard', label: '工作台', icon: LayoutDashboard },
  { href: '/plans/new', label: '新建计划', icon: PlusCircle },
  { href: '/statistics', label: '数据统计', icon: BarChart3 },
]

export function Navbar() {
  const [scrolled, setScrolled] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const pathname = usePathname()

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return (
    <nav
      className={`fixed top-0 left-0 right-0 z-50 px-6 md:px-12 h-16 flex items-center justify-between transition-all duration-300 ${
        scrolled ? 'bg-[#FAF8F5]/85 backdrop-blur-xl shadow-md' : 'bg-transparent'
      }`}
    >
      <Link href="/" className="flex items-center gap-2.5">
        <BookOpen className="w-6 h-6 text-[#8B5E3C]" />
        <span className="font-display text-xl text-[#8B5E3C]">彩笺寄</span>
      </Link>

      {/* Desktop Nav */}
      <div className="hidden md:flex items-center gap-1">
        {navItems.map((item) => {
          const Icon = item.icon
          const isActive = pathname === item.href
          return (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 ${
                isActive
                  ? 'bg-[#8B5E3C] text-white'
                  : 'text-[#5A5048] hover:text-[#8B5E3C] hover:bg-[#F5EDE3]'
              }`}
            >
              <Icon className="w-4 h-4" />
              {item.label}
            </Link>
          )
        })}
      </div>

      {/* Mobile Menu Button */}
      <button
        className="md:hidden p-2 rounded-lg hover:bg-[#F5F0EB] transition-colors"
        onClick={() => setMobileOpen(!mobileOpen)}
      >
        {mobileOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
      </button>

      {/* Mobile Nav */}
      {mobileOpen && (
        <div className="absolute top-16 left-0 right-0 bg-white border-b border-[#E5DDD4] shadow-lg md:hidden">
          <div className="p-4 space-y-1">
            {navItems.map((item) => {
              const Icon = item.icon
              const isActive = pathname === item.href
              return (
                <Link
                  key={item.href}
                  href={item.href}
                  onClick={() => setMobileOpen(false)}
                  className={`flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all ${
                    isActive
                      ? 'bg-[#8B5E3C] text-white'
                      : 'text-[#5A5048] hover:bg-[#F5F0EB]'
                  }`}
                >
                  <Icon className="w-5 h-5" />
                  {item.label}
                </Link>
              )
            })}
          </div>
        </div>
      )}
    </nav>
  )
}
